#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-12-16"
pages_build_output_dir = "./build/client"
send_metrics = false
